const shared = {
  author: require("./author"),
  categories: require("./categories"),
  charset: require("./charset"),
  description: require("./description"),
  dir: require("./dir"),
  display: require("./display"),
  elementId: require("./elementId"),
  isEnv: require("./isEnv"),
  keywords: require("./keywords"),
  lang: require("./lang"),
  name: require("./name"),
  orientation: require("./orientation"),
  origin: require("./origin"),
  path: require("./path"),
  port: require("./port"),
  resource: require("./resource"),
  settings: require("./settings"),
  socialMedia: require("./socialMedia"),
  style: require("./style"),
  type: require("./type"),
  url: require("./url"),
  viewport: require("./viewport"),
};

module.exports = shared;
